version: '3.8'

services:
  database:
    image: postgres:16.4-alpine
    container_name: database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Cryt0W4ll3t!
      POSTGRES_DB: crypto_wallet
    expose:
      - 5432
    ports:
      - "5432:5432"

  transaction-request:
    build:
      context: ./transaction_request_service
      dockerfile: .Dockerfile
    expose:
      - "5002"
    ports:
      - "5002:5002"

  transaction-execution:
    build:
      context: ./transaction_execution_service
      dockerfile: .Dockerfile
    expose:
      - "5003"
    ports:
      - "5003:5003"
